# src/Mgn/CoreBundle/Resources/config/services.yml

services:

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.loader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

    mgn.config:
        class: Mgn\CoreBundle\Twig\Extension\ConfigExtension
        arguments: [@doctrine]
        tags:
            -  { name: twig.extension }

    mgn.theme:
        class: Mgn\CoreBundle\Twig\Extension\ThemeExtension
        arguments: [@security.context, @doctrine, @mgn.config]
        tags:
            -  { name: twig.extension }

    mgn.mcode:
        class: Mgn\CoreBundle\Twig\Extension\MCodeExtension
        arguments: [@mgn.config]
        tags:
            - { name: twig.extension }

    mgn.mcode.video:
        class: Mgn\CoreBundle\Twig\Extension\MCodeVideoExtension
        arguments: [@mgn.config]
        tags:
            - { name: twig.extension }

    mgn.pagination:
        class: Mgn\CoreBundle\Twig\Extension\PaginationExtension
        arguments: [@mgn.config]
        tags:
            - { name: twig.extension }

    mgn.datetime:
        class: Mgn\CoreBundle\Twig\Extension\DatetimeExtension
        tags:
            - { name: twig.extension }

    mgn.fileExists:
        class: Mgn\CoreBundle\Twig\Extension\FileExistsExtension
        tags:
            - { name: twig.extension }

    mgn.avatar:
        class: Mgn\CoreBundle\Twig\Extension\AvatarExtension
        arguments: [@mgn.theme]
        tags:
            - { name: twig.extension }